name = "voygent-themed"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "voygent-themed"
database_id = "62077781-9458-4206-a5c6-f38dc419e599"

[ai]
binding = "AI"

[vars]
PROVIDER_MODE = "cheap"

# Secrets set via `wrangler pages secret put` or .dev.vars for local
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# AMADEUS_CLIENT_ID
# AMADEUS_CLIENT_SECRET
# SERPER_API_KEY
# TAVILY_API_KEY
