/**
 * TypeScript interfaces for Trip Options Display
 * Feature: 004-finish-the-full
 *
 * These interfaces define the contract between the backend API
 * (/api/trips POST) and the frontend display function (displayTripOptions).
 */

/**
 * Single trip option generated by the AI
 * Represents one possible itinerary choice (e.g., "Heritage Highlights - 7 Days")
 */
export interface TripOption {
  /** Unique key for this option (A, B, C, or D) */
  key: string;

  /** Human-readable title (e.g., "Heritage Highlights - 7 Days") */
  title: string;

  /** Brief description of this trip option (2-3 sentences) */
  description: string;

  /** Trip style (e.g., "Guided Experience", "Self-Guided Adventure") */
  style: string;

  /** List of cities included in this trip */
  cities: string[];

  /** Estimated total budget in USD */
  estimated_budget: number;

  /** Key highlights and activities for this trip */
  highlights: string[];

  /** Optional: Detailed day-by-day itinerary */
  itinerary?: ItineraryDay[];

  /** Optional: Cost breakdown by category */
  cost_breakdown?: CostBreakdown;
}

/**
 * Single day in an itinerary
 */
export interface ItineraryDay {
  /** Day number (1-based) */
  day: number;

  /** City/location for this day */
  city: string;

  /** Brief title for the day (e.g., "Arrival & Old Town") */
  title?: string;

  /** List of activities for this day */
  activities: string[];

  /** Accommodation information */
  accommodation?: {
    name: string;
    type: string; // "hotel", "b&b", "hostel", etc.
    estimated_cost_per_night?: number;
  };

  /** Travel segment to next location (if applicable) */
  travel_to_next?: {
    mode: string; // "drive", "train", "flight", "ferry"
    destination: string;
    duration_hours: number;
    estimated_cost?: number;
  };
}

/**
 * Cost breakdown by category
 */
export interface CostBreakdown {
  /** Roundtrip flight costs */
  flights?: {
    total: number;
    per_person: number;
    adults: number;
    route: string; // e.g., "JFK → EDI → JFK"
    details?: string;
  };

  /** Hotel costs across all nights */
  hotels?: {
    total: number;
    nights: number;
    cities: number;
    average_per_night: number;
    details?: string;
  };

  /** Rental car estimate (not from live API) */
  rental_car?: {
    total: number;
    days: number;
    daily_rate: number;
    is_estimate: boolean; // Always true for rental car
    details?: string;
  };

  /** Total estimated cost */
  total: number;

  /** Total per person (if multiple travelers) */
  per_person: number;

  /** Currency code (always "USD" for now) */
  currency: string;
}

/**
 * Complete response from /api/trips POST
 */
export interface TripGenerationResponse {
  /** Unique trip ID */
  id: string;

  /** Theme used for this trip */
  theme: string;

  /** Normalized intake data */
  intake: Record<string, any>;

  /** Array of 2-4 trip options */
  options: TripOption[];

  /** Research findings from earlier phase */
  research?: ResearchStep[];

  /** Diagnostic information for debugging */
  diagnostics?: {
    intake?: any;
    options?: any;
  };
}

/**
 * Research step from /api/research
 */
export interface ResearchStep {
  step: string;
  query?: string;
  summary?: string;
  sources?: string[];
  error?: string;
}

/**
 * State management for selected trip option
 */
export interface TripSelectionState {
  /** Currently selected option key */
  selectedOptionKey: string | null;

  /** Full trip data */
  tripData: TripGenerationResponse | null;

  /** Currently displayed option (cached for quick access) */
  currentOption: TripOption | null;
}

/**
 * Parameters passed to quote request modal
 */
export interface QuoteRequestContext {
  /** Trip ID to attach quote to */
  tripId: string;

  /** Selected option key (A, B, C, or D) */
  selectedOptionKey: string;

  /** Estimated budget for context */
  estimatedBudget: number;

  /** Optional: Theme for context */
  theme?: string;
}
